sdf

diff --git a/.github/workflows/validate-pr.yml b/.github/workflows/validate-pr.yml
--- a/.github/workflows/validate-pr.yml
+++ b/.github/workflows/validate-pr.yml
@@ -15,24 +15,17 @@ jobs:
       - name: Find app_theme.json
         id: find_file
         run: |
-          app_theme_file=$(git ls-files | grep "app_theme.json" || true)
-          echo "app_theme_file=$app_theme_file" >> $GITHUB_ENV
-
-      - name: Check for changes in app_theme.json
-        id: check_changes
-        run: |
-          if [ -n "$app_theme_file" ] && git diff --name-only origin/main...HEAD | grep -q "$app_theme_file"; then
-            echo "app_theme.json has changes."
-            echo "changed=true" >> $GITHUB_ENV
-          else
-            echo "No changes in app_theme.json."
-            echo "changed=false" >> $GITHUB_ENV
+          app_theme_file=$(find . -name "app_theme.json" || true)
+          if [ -z "$app_theme_file" ]; then
+            echo "app_theme.json not found."
+            exit 0
           fi
+          echo "Found app_theme.json at $app_theme_file"
+          echo "::set-output name=app_theme_file::$app_theme_file"
 
       - name: Check for '#' character in app_theme.json
-        if: env.changed == 'true'
         run: |
-          filtered_content=$(jq 'del(.globalColorTheme, .gradients, .elevation, .igniteTheme)' "$app_theme_file")
+          filtered_content=$(jq 'del(.globalColorTheme, .gradients, .elevation, .igniteTheme)' "${{ steps.find_file.outputs.app_theme_file }}")
           
           if echo "$filtered_content" | grep -q "#"; then
             echo "Hash (#) character found in app_theme.json."
